# Generated by Django 2.0.1 on 2019-05-26 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_project', '0002_auto_20190526_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Gün')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 729563, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tələbənin sərbəst işi',
                'verbose_name_plural': 'Tələbələrin sərbəst işləri',
            },
        ),
        migrations.CreateModel(
            name='StudentMonitoringPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(verbose_name='Bal')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 730432, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_monitoring_points', to='sms_project.Monitoring')),
            ],
            options={
                'verbose_name': 'Tələbənin sərbəst işi',
                'verbose_name_plural': 'Tələbələrin sərbəst işləri',
            },
        ),
        migrations.AlterModelOptions(
            name='studentwork',
            options={'verbose_name': 'Tələbənin sərbəst işi', 'verbose_name_plural': 'Tələbələrin sərbəst işləri'},
        ),
        migrations.AddField(
            model_name='studentwork',
            name='point',
            field=models.PositiveIntegerField(default=1, verbose_name='Bal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 721764, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 725760, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='diary',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 725663, tzinfo=utc), verbose_name='Gün'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 716327, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 718798, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 723706, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='notparticipating',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 726720, tzinfo=utc), verbose_name='Gün'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 718003, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 717188, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 720102, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 728608, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 721093, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 724789, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 722562, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 727579, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='lastday',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 20, 17, 17, 727478, tzinfo=utc), verbose_name='Son Gün'),
        ),
        migrations.AddField(
            model_name='studentmonitoringpoint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_monitoring_points', to='sms_project.Student'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='group_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='sms_project.GroupSubject'),
        ),
    ]
